############################
#Accomplishes the following build tasks
#
#1) Runs the cloudformation template to create the necessary resources
#2) Runs python coverage function to generate Auto HTML documentation
##) Runs unit tests of lambda functions, checks aws resources created
#
#
############################
version: 0.2

phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo Entered the install phase...

      - BUILD_ENVIRONMENT=prod-ratings
      - BACKUP_DYNAMODB_FUNCTION_NAME="${BUILD_ENVIRONMENT}-backend-backup-dynamodb"
      - LAMBDA_FUNCTION_NAME="${BUILD_ENVIRONMENT}-backend-lambda-poll"
      - RATINGS_UPDATE_STACK="${BUILD_ENVIRONMENT}-backend"           
      - REPO_NAME=ratings
      - pip install -r tests/requirements_prod.txt
      - ls -l
    finally:

  build:
    commands:
      - echo Defined build variables
      - echo $BUILD_ENVIRONMENT
      - echo $BACKUP_DYNAMODB_FUNCTION_NAME
      - echo $LAMBDA_FUNCTION_NAME
      - echo $RATINGS_UPDATE_STACK
      - echo $REPO_NAME




      #CODEBUILD_SRC_DIR_BuildDevBackend = 
      #where output lambda artifacts are stored from dev CodeBuild

      ################################################
      #
      #updates zip deployment package for ratings dynamodb
      #table update script
      #################################################
      - aws lambda update-function-code
        --function-name $LAMBDA_FUNCTION_NAME
        --zip-file "fileb://${CODEBUILD_SRC_DIR_BuildDevBackend}/deploypkg/built_lambda.zip"

      #wait for update-function-code to be complete
      - aws lambda wait function-updated --function-name $LAMBDA_FUNCTION_NAME

      #changes lambda handler to scripts/reddit_ratings.py
      #lambda_handler function
      - aws lambda update-function-configuration
        --function-name $LAMBDA_FUNCTION_NAME
        --handler "reddit_ratings.lambda_handler"


      ################################################
      #
      #updates zip deployment package for backup update script
      #################################################
      - aws lambda update-function-code
        --function-name $BACKUP_DYNAMODB_FUNCTION_NAME
        --zip-file "fileb://${CODEBUILD_SRC_DIR_BuildDevBackend}/backup_dynamodb_ratings.zip"

      #wait for update-function-code to be complete
      - aws lambda wait function-updated --function-name $BACKUP_DYNAMODB_FUNCTION_NAME


      #changes lambda handler to scripts/reddit_ratings.py
      #lambda_handler function
      - aws lambda update-function-configuration
        --function-name $BACKUP_DYNAMODB_FUNCTION_NAME
        --handler "backup_dynamodb_ratings.lambda_handler"

      #syncronously invoke the lambda backup function once
      #with cloudwatch timer event payload
      - aws lambda invoke --function-name $BACKUP_DYNAMODB_FUNCTION_NAME
        --payload file://util/lambda_cw_event.json
        "${BACKUP_DYNAMODB_FUNCTION_NAME}_output.json"


      #syncronously invoke the lambda ratings poll
      - aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME
        --payload file://util/lambda_cw_event.json
        "${LAMBDA_FUNCTION_NAME}_output.json"

      - python -m unittest tests/test_prod_ratings_backend.py


      #merges dev branch into master now that all tests have
      #been passed and artifacts created
      - aws codecommit merge-branches-by-fast-forward
        --source-commit-specifier dev
        --destination-commit-specifier master
        --repository-name $REPO_NAME




  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - ./logs/*
