AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a CodePipeline for a CI/CD pipeline
Parameters:

  #Default project name that
  #the git repo will be called
  ProjectName:
    Type: String
    Default: ratings

  RepositoryDescription:
    Type: String
    Default: Personal Website hosted using S3

Resources:

  GitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
        RepositoryDescription:
            !Join [' ', ['Repo for ', !Ref ProjectName,
            !Ref RepositoryDescription]]
        RepositoryName: !Ref ProjectName
  
  ##########################
  #Build logs for ProdCodeBuildDeploy
  #CodeBuild stage
  #
  #
  ##########################
  ProdArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
         !Join ['', ['prod-build-', !Ref ProjectName]]
      Tags:
        -
          Key: stage
          Value: prod
        -
          Key: retain
          Value: "false"
        -
          Key: project
          Value: !Ref ProjectName


####################################
#Role that will be assumed when
#CodeBuild runs for Prod
#
####################################
  ProdCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess

      Path: /
      Policies:
          - PolicyName: CodeBuildCustomerManaged
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: IAMallow
                  Effect: Allow
                  #######################################
                  #Allowing lambda to perform a PutItem on
                  #DynamoDB
                  #
                  #######################################
                  Action:
                    - iam:PassRole
                    - iam:CreateRole
                    - iam:GetRole
                    - iam:UpdateAssumeRolePolicy
                    - iam:DetachRolePolicy
                    - iam:DeleteRolePolicy
                    - iam:PutRolePolicy
                  Resource:
                    - "*"
                #######################
                #Permissions needed for aws
                #CodeBuild service to run
                #######################
                - Sid: S3WebsiteCreation
                  Effect: Allow
                  #######################################
                  #Allowing CodeBuild to create
                  #resources necessary for s3 static webpage
                  #
                  #######################################
                  Action:
                    - s3:CreateBucket
                    - s3:DeleteBucket
                    - s3:DeleteBucketPolicy
                    - s3:DeleteObject
                    - s3:GetBucketAcl
                    - s3:GetBucketLocation
                    - s3:GetObject
                    - s3:GetObjectVersion
                    - s3:ListBucket
                    - s3:ListAllMyBuckets
                    - s3:PutBucketCORS
                    - s3:PutBucketPolicy
                    - s3:PutBucketWebsite
                    - s3:PutObject

                  Resource:
                    - "*"

                #######################
                #Permissions needed for aws
                #CodeBuild to create/delete stacks
                #######################
                - Sid: CodeBuildCfCreation
                  Effect: Allow
                  #######################################
                  #Allowing CodeBuild to create
                  #resources necessary for s3 static webpage
                  #
                  #######################################
                  Action:
                    - cloudformation:CreateStack
                    - cloudformation:DeleteStack
                    - cloudformation:DescribeStacks
                  Resource:
                    - "*"

                #######################
                #Permissions needed for aws
                #CodeBuild to assume the production
                #cross account role
                #######################
                - Sid: AssumeProdAccountRole
                  Effect: Allow
                  #######################################
                  #Allowing CodeBuild to update
                  #resources necessary for s3 static webpage
                  #
                  #######################################
                  Action:
                    - sts:AssumeRole
                  Resource:
                    - "*"


  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      #List of Policies for Code Pipeline
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
          - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
          - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
          - PolicyName: PipelinePassRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: IamPassRoleAllow
                  Effect: Allow
                  #######################################
                  #Allowing lambda to perform a PutItem on
                  #DynamoDB
                  #
                  #######################################
                  Action:
                    - iam:PassRole
                  Resource:
                    - "*"


Outputs:
  CodeCommitURL:
    Description: CodeCommit URL
    Value:
      Fn::Join:
        - ""
        - - "https://console.aws.amazon.com/codepipeline/home?region="
          - Ref: AWS::Region
          - "#/repository/"
          - Ref: AWS::StackName
          - "/browse/HEAD/--/"
  GitRepoName:
    Description: Name of the git repository
    Value: !GetAtt GitRepo.Name
